In [2]:
!pip3 install catboost --user

Looking in indexes: http://yum.tbsite.net/pypi/simple/
You should consider upgrading via the 'pip install --upgrade pip' command.


In [3]:
!pip3 install lightgbm --user

Looking in indexes: http://yum.tbsite.net/pypi/simple/
     |████████████████████████████████| 1.8MB 18.2MB/s 
     |████████████████████████████████| 22.2MB 20.5MB/s 
     |████████████████████████████████| 307kB 18.4MB/s 
You should consider upgrading via the 'pip install --upgrade pip' command.


In [5]:
!pip3 install xgboost --user

Looking in indexes: http://yum.tbsite.net/pypi/simple/
     |████████████████████████████████| 157.5MB 24.7MB/s 
You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
import os
import gc
import math

import pandas as pd
import numpy as np

import lightgbm as lgb
import xgboost as xgb
# from catboost import CatBoostRegressor
from sklearn.linear_model import SGDRegressor, LinearRegression, Ridge
from sklearn.preprocessing import MinMaxScaler


from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.metrics import log_loss
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from tqdm import tqdm
import matplotlib.pyplot as plt
import time
import warnings
warnings.filterwarnings('ignore')

In [16]:
#读取数据
train = pd.read_csv('train.csv')
test=pd.read_csv('testA.csv')
train.head(50)

id                                  heartbeat_signals  label
0    0  0.9912297987616655,0.9435330436439665,0.764677...    0.0
1    1  0.9714822034884503,0.9289687459588268,0.572932...    0.0
2    2  1.0,0.9591487564065292,0.7013782792997189,0.23...    2.0
3    3  0.9757952826275774,0.9340884687738161,0.659636...    0.0
4    4  0.0,0.055816398940721094,0.26129357194994196,0...    2.0
5    5  1.0,0.8675497147252661,0.5128848334259041,0.36...    0.0
6    6  0.9505940730409403,0.9166910623948625,0.848396...    2.0
7    7  0.8681707532149519,0.8318642354644805,0.531120...    2.0
8    8  0.9792414410794537,0.6155508397973931,0.632268...    3.0
9    9  0.9917559671326545,1.0,0.9740518898684873,0.93...    2.0
10  10  0.7776075929954396,0.6920800485100926,0.602560...    3.0
11  11  0.0,0.12046752033856772,0.285957554191089,0.41...    0.0
12  12  0.9252141321895656,0.8779924675549222,0.345761...    1.0
13  13  1.0,0.9458110981341936,0.7666455363406568,0.50...    2.0
14  14  0.814321395420132,0.7402609622914397,0.6550196...    3.0
15  15  0.9605437317666576,0.45848775058496943,0.01548...    0.0
16  16  1.0,0.9258682803508748,0.5385424415808975,0.16...    0.0
17  17  0.9946861950265535,0.7767233240713837,0.290470...    0.0
18  18  0.8468832809320361,0.8001808672219326,0.845490...    3.0
19  19  1.0,0.6653359171851763,0.4918530963296747,0.31...    0.0
20  20  0.9388597089086641,0.8218202952999004,0.381731...    0.0
21  21  0.6372943707453936,0.5307822734972873,0.407088...    2.0
22  22  0.9770736169248465,0.9318023120687151,0.685364...    0.0
23  23  0.9656298251848078,0.9258896645858993,0.883854...    3.0
24  24  0.7896311490368609,0.8660372318969782,0.826602...    2.0
25  25  0.9705705413651573,0.8739646045967879,0.650057...    0.0
26  26  0.5712493340311691,0.5483748624931888,0.444244...    0.0
27  27  0.7247158534309897,0.6382835708051017,0.519766...    2.0
28  28  0.9940144977756433,0.6095294072171888,0.609748...    3.0
29  29  1.0,0.9138801183964681,0.5592567902002209,0.35...    0.0
30  30  1.0,0.7896401529065578,0.32915966257059437,0.0...    0.0
31  31  0.973779814365007,0.9146235912543943,0.6876292...    0.0
32  32  1.0,0.9131951674632317,0.19352237143670928,0.1...    0.0
33  33  1.0,0.9621378527718282,0.4645698048221909,0.0,...    0.0
34  34  0.992127162875099,0.9182304297710062,0.4741666...    0.0
35  35  1.0,0.6362812642906739,0.4894398976958974,0.31...    0.0
36  36  0.9519057256450161,0.8936911059469604,0.618726...    0.0
37  37  1.0,0.602820277317863,0.5898794991826486,0.630...    3.0
38  38  1.0,0.9232938408986751,0.6111800114372911,0.26...    0.0
39  39  0.9623771986033592,0.985295787706603,0.5228767...    0.0
40  40  1.0,0.9294541938071404,0.6432301471817717,0.35...    0.0
41  41  0.5364708939230977,0.4697546761364632,0.358793...    0.0
42  42  1.0,0.9537769668410081,0.8114339837172381,0.63...    0.0
43  43  0.9792414410794537,0.8707169911167203,0.554413...    0.0
44  44  1.0,0.8707169911167203,0.2857544845172509,0.05...    0.0
45  45  1.0,0.9347085568669242,0.3039423418627903,0.04...    0.0
46  46  0.9410763734254239,1.0,0.9555815217969701,0.88...    2.0
47  47  0.783176191164021,0.7375189809408202,0.5264167...    2.0
48  48  0.0,0.27287259236715444,0.43812110113111624,0....    0.0
49  49  0.9632882296220554,0.7556928186144114,0.558132...    0.0

In [8]:
test.head()

id                                  heartbeat_signals
0  100000  0.9915713654170097,1.0,0.6318163407681274,0.13...
1  100001  0.6075533139615096,0.5417083883163654,0.340694...
2  100002  0.9752726292239277,0.6710965234906665,0.686758...
3  100003  0.9956348033996116,0.9170249621481004,0.521096...
4  100004  1.0,0.8879490481178918,0.745564725322326,0.531...

In [9]:
#数据预处理


def reduce_mem_usage(df):
    start_mem = df.memory_usage().sum() / 1024**2 
    print('Memory usage of dataframe is {:.2f} MB'.format(start_mem))
    
    for col in df.columns:
        col_type = df[col].dtype
        
        if col_type != object:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)
        else:
            df[col] = df[col].astype('category')

    end_mem = df.memory_usage().sum() / 1024**2 
    print('Memory usage after optimization is: {:.2f} MB'.format(end_mem))
    print('Decreased by {:.1f}%'.format(100 * (start_mem - end_mem) / start_mem))
    
    return df

In [10]:
# 简单预处理
train_list = []

for items in train.values:
    train_list.append([items[0]] + [float(i) for i in items[1].split(',')] + [items[2]])

train = pd.DataFrame(np.array(train_list))
train.columns = ['id'] + ['s_'+str(i) for i in range(len(train_list[0])-2)] + ['label']
train = reduce_mem_usage(train)

test_list=[]
for items in test.values:
    test_list.append([items[0]] + [float(i) for i in items[1].split(',')])

test = pd.DataFrame(np.array(test_list))
test.columns = ['id'] + ['s_'+str(i) for i in range(len(test_list[0])-1)]
test = reduce_mem_usage(test)

Memory usage of dataframe is 157.93 MB
Memory usage after optimization is: 39.67 MB
Decreased by 74.9%
Memory usage of dataframe is 31.43 MB
Memory usage after optimization is: 7.90 MB
Decreased by 74.9%


In [13]:
#训练数据/测试数据准备

x_train = train.drop(['id','label'], axis=1)
y_train = train['label']
x_test=test.drop(['id'], axis=1)

In [14]:
#模型训练

def abs_sum(y_pre,y_tru):
    y_pre=np.array(y_pre)
    y_tru=np.array(y_tru)
    loss=sum(sum(abs(y_pre-y_tru)))
    return loss

In [15]:
def cv_model(clf, train_x, train_y, test_x, clf_name):
    folds = 5
    seed = 2021
    kf = KFold(n_splits=folds, shuffle=True, random_state=seed)
    test = np.zeros((test_x.shape[0],4))

    cv_scores = []
    onehot_encoder = OneHotEncoder(sparse=False)
    for i, (train_index, valid_index) in enumerate(kf.split(train_x, train_y)):
        print('************************************ {} ************************************'.format(str(i+1)))
        trn_x, trn_y, val_x, val_y = train_x.iloc[train_index], train_y[train_index], train_x.iloc[valid_index], train_y[valid_index]
        
        if clf_name == "lgb":
            train_matrix = clf.Dataset(trn_x, label=trn_y)
            valid_matrix = clf.Dataset(val_x, label=val_y)

            params = {
                'boosting_type': 'gbdt',
                'objective': 'multiclass',
                'num_class': 4,
                'num_leaves': 2 ** 5,
                'feature_fraction': 0.8,
                'bagging_fraction': 0.8,
                'bagging_freq': 4,
                'learning_rate': 0.1,
                'seed': seed,
                'nthread': 28,
                'n_jobs':24,
                'verbose': -1,
            }

            model = clf.train(params, 
                      train_set=train_matrix, 
                      valid_sets=valid_matrix, 
                      num_boost_round=2000, 
                      verbose_eval=100, 
                      early_stopping_rounds=200)
            val_pred = model.predict(val_x, num_iteration=model.best_iteration)
            test_pred = model.predict(test_x, num_iteration=model.best_iteration) 
            
        val_y=np.array(val_y).reshape(-1, 1)
        val_y = onehot_encoder.fit_transform(val_y)
        print('预测的概率矩阵为：')
        print(test_pred)
        test += test_pred
        score=abs_sum(val_y, val_pred)
        cv_scores.append(score)
        print(cv_scores)
    print("%s_scotrainre_list:" % clf_name, cv_scores)
    print("%s_score_mean:" % clf_name, np.mean(cv_scores))
    print("%s_score_std:" % clf_name, np.std(cv_scores))
    test=test/kf.n_splits

    return test

In [17]:
def lgb_model(x_train, y_train, x_test):
    lgb_test = cv_model(lgb, x_train, y_train, x_test, "lgb")
    return lgb_test
lgb_test = lgb_model(x_train, y_train, x_test)

************************************ 1 ************************************
[LightGBM] [Warning] num_threads is set with n_jobs=24, nthread=28 will be ignored. Current value: num_threads=24
Training until validation scores don't improve for 200 rounds
[100]	valid_0's multi_logloss: 0.0525735
[200]	valid_0's multi_logloss: 0.0422444
[300]	valid_0's multi_logloss: 0.0407076
[400]	valid_0's multi_logloss: 0.0420398
Early stopping, best iteration is:
[289]	valid_0's multi_logloss: 0.0405457
预测的概率矩阵为：
[[9.99969791e-01 2.85197261e-05 1.00341946e-06 6.85357631e-07]
 [7.93287264e-05 7.69060914e-04 9.99151590e-01 2.00810971e-08]
 [5.75356884e-07 5.04051497e-08 3.15322414e-07 9.99999059e-01]
 ...
 [6.79267940e-02 4.30206297e-04 9.31640185e-01 2.81516302e-06]
 [9.99960477e-01 3.94098074e-05 8.34030725e-08 2.94638661e-08]
 [9.88705846e-01 2.14081630e-03 6.67418381e-03 2.47915423e-03]]
[607.0736049372185]
************************************ 2 ************************************
[LightGBM] [Warnin

In [20]:
temp=pd.DataFrame(lgb_test)
result=pd.read_csv('sample_submit.csv')
result['label_0']=temp[0]
result['label_1']=temp[1]
result['label_2']=temp[2]
result['label_3']=temp[3]
result.to_csv('submit.csv',index=False)